name: Test Self-Hosted Runners

on:
  workflow_dispatch:

jobs:
  test-k0s:
    runs-on: [self-hosted, k0s]
    steps:
    - name: Runner Information
      run: |
        echo "=== Testing runner: k0s ==="
        echo "Hostname: $(hostname)"
        echo "IP Address: $(hostname -I | awk '{print $1}')"
        echo "OS: $(lsb_release -d | cut -f2)"
        echo "Kernel: $(uname -r)"
        echo "CPU: $(nproc) cores"
        echo "Memory: $(free -h | grep Mem | awk '{print $2}')"
        echo "Disk: $(df -h / | tail -1 | awk '{print $4}') available"
        
    - name: Check Docker
      run: |
        echo "=== Docker Status ==="
        docker --version
        docker ps
        
    - name: Check System Resources
      run: |
        echo "=== System Resources ==="
        echo "CPU Usage:"
        top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}'
        echo ""
        echo "Memory Usage:"
        free -m
        echo ""
        echo "Disk Usage:"
        df -h
        
    - name: Network Test
      run: |
        echo "=== Network Connectivity ==="
        ping -c 3 github.com || echo "Ping failed"
        echo ""
        curl -s https://api.github.com/rate_limit | jq .rate || echo "API check failed"
        
    - name: Create test file
      run: |
        echo "Runner k0s is working correctly!" > /tmp/runner-test-k0s.txt
        cat /tmp/runner-test-k0s.txt

  test-k3s:
    runs-on: [self-hosted, k3s]
    steps:
    - name: Test k3s Runner
      run: |
        echo "=== Testing runner: k3s ==="
        echo "Runner k3s is working correctly!"
        hostname
        docker --version

  test-kind:
    runs-on: [self-hosted, kind]
    steps:
    - name: Test kind Runner
      run: |
        echo "=== Testing runner: kind ==="
        echo "Runner kind is working correctly!"
        hostname
        docker --version

  test-kubeadm:
    runs-on: [self-hosted, kubeadm]
    steps:
    - name: Test kubeadm Runner
      run: |
        echo "=== Testing runner: kubeadm ==="
        echo "Runner kubeadm is working correctly!"
        hostname
        docker --version

  test-microk8s:
    runs-on: [self-hosted, microk8s]
    steps:
    - name: Test microk8s Runner
      run: |
        echo "=== Testing runner: microk8s ==="
        echo "Runner microk8s is working correctly!"
        hostname
        docker --version

  test-minikube:
    runs-on: [self-hosted, minikube]
    steps:
    - name: Test minikube Runner
      run: |
        echo "=== Testing runner: minikube ==="
        echo "Runner minikube is working correctly!"
        hostname
        docker --version

  test-rke:
    runs-on: [self-hosted, rke]
    steps:
    - name: Test rke Runner
      run: |
        echo "=== Testing runner: rke ==="
        echo "Runner rke is working correctly!"
        hostname
        docker --version

  test-openshift:
    runs-on: [self-hosted, openshift]
    steps:
    - name: Test openshift Runner
      run: |
        echo "=== Testing runner: openshift ==="
        echo "Runner openshift is working correctly!"
        hostname
        docker --version

  summary:
    needs: [test-k0s, test-k3s, test-kind, test-kubeadm, test-microk8s, test-minikube, test-rke, test-openshift]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Summary
      run: |
        echo "## Runner Test Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Runner | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|--------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| k0s | ${{ needs.test-k0s.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| k3s | ${{ needs.test-k3s.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| kind | ${{ needs.test-kind.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| kubeadm | ${{ needs.test-kubeadm.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| microk8s | ${{ needs.test-microk8s.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| minikube | ${{ needs.test-minikube.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| rke | ${{ needs.test-rke.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| openshift | ${{ needs.test-openshift.result }} |" >> $GITHUB_STEP_SUMMARY